### ISSUE TITLE
Swift 3 Updates

### ISSUE THREAD

**Issue by andreyrd** [marty-suzuki/MisterFusion#27]
Hey, I know you have a beta/swift3 branch, but it's already out of date. I'm working on updating it to the latest Syntax, and I'll open a pull request when I'm done, but I've run into one issue.

https://developer.apple.com/library/prerelease/content/releasenotes/General/iOS10APIDiffs/Swift/UIKit.html

`NSLayoutAttribute.Baseline` has been removed from UIKit. 

Based on https://developer.apple.com/reference/appkit/nslayoutattribute/nslayoutattributebaseline it appears that Baseline is equivalent to LastBaseline? I see that you already have a MisterFusion defined for LastBaseline.

```
public var Baseline: MisterFusion { return createMisterFusion(.baseline) }   
public var LastBaseline: MisterFusion { return createMisterFusion(.lastBaseline) }
```

Should I just define Baseline as LastBaseline?

```
public var Baseline: MisterFusion { return createMisterFusion(.lastBaseline) }   
public var LastBaseline: MisterFusion { return createMisterFusion(.lastBaseline) }
```

Or should we just remove Baseline and let people update their apps accordingly, since it has been removed in iOS 10?

```
public var LastBaseline: MisterFusion { return createMisterFusion(.lastBaseline) }
```

**Comment by marty-suzuki** [comment]
Hi, @andreyrd 
I've updated beta/swift3 to the latest syntax.


> it appears that Baseline is equivalent to LastBaseline?

I tried to the baseline equals to the lastBaseline. in xcode7.3.1 playgrounds.
![baseline](https://cloud.githubusercontent.com/assets/2082134/18077192/d37fd5c6-6ebe-11e6-86c8-dddfa5455c45.png)

It seems equal.
So, I defined baseline as obsoleted property.

```swift
@available(iOS, obsoleted: 7.0, renamed: "lastBaseline")
@objc(Baseline)
public var baseline: MisterFusion { return createMisterFusion(withAttribute: .lastBaseline) }
```

baseline will have been automatically converted to lastBaseline.
