### ISSUE TITLE
Annotate addLayout*() methods with @discardableResult

### ISSUE THREAD

**Issue by andreyrd** [marty-suzuki/MisterFusion#33]
Since Swift 3, warnings for an unused return value are on by default: http://useyourloaf.com/blog/swift-3-warning-of-unused-result/

Most of the time, I don't need to store the result of methods such as `addLayoutSubview`. You should consider annotating methods with @discardableResult wherever it makes sense.

**Comment by marty-suzuki** [comment]
Hi, @andreyrd!
Thank you for your issue!

I've released 2.0.0!
