### ISSUE TITLE
'shared' is unavailable: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by aftabalam81** [marty-suzuki/MisterFusion#47]
let traitCollection = UIApplication.shared.keyWindow?.traitCollection
This line has started giving me an error, it was working perfectly fine a day ago though, nothing changed and this error started appearing.
swift 4.0
XCode 9.4
MacOS Mojave

**Comment by aftabalam81** [comment]
I did add a TodayView Activity and had my pod file to be added in both targets using #abstract_target, can that be the reason?

**Comment by marty-suzuki** [comment]
@aftabalam81 
Sorry for late response 😅
I've fixed this issue with v4.0.1 🛠
